- name: Add nodejs repo
  shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

- name: Yarn gpg
  shell: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

- name: Add yarn repo
  shell: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

- name: Apt update
  apt:
    update_cache: yes

- name: Install required packages
  apt: name={{item}} state=installed
  with_items:
       - git-core
       - curl
       - zlib1g-dev
       - build-essential
       - libssl-dev
       - libreadline-dev
       - libyaml-dev
       - libsqlite3-dev
       - sqlite3
       - libxml2-dev
       - libxslt1-dev
       - libcurl4-openssl-dev
       - python-software-properties
       - libffi-dev
       - nodejs
       - yarn

- name: Clone rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    version: master
    dest: ~/.rbenv
    accept_hostkey: yes
  # ssh-agent doesn't allow key to pass through remote sudo commands.
  become: no

- name: Add variables to bashrc
  shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc

- name: Add variables to bashrc
  shell: echo 'eval "$(rbenv init -)"' >> ~/.bashrc

- name: Source bashrc
  shell: source /root/.bashrc
  args:
    executable: /bin/bash

- name: Clone ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    version: master
    dest: ~/.rbenv/plugins/ruby-build
    accept_hostkey: yes
  # ssh-agent doesn't allow key to pass through remote sudo commands.
  become: no

- name: Add variables to bashrc
  shell: echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc

- name: Source bashrc
  shell: source /root/.bashrc
  args:
    executable: /bin/bash

- name: Install ruby
  shell: . /root/.bashrc && rbenv install 2.5.0

- name: Set global ruby version
  shell: . /root/.bashrc && rbenv global 2.5.0

- name: Install bundler
  shell: . /root/.bashrc && gem install bundler

- name: Node repo
  shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

- name: Install the package nodejs
  apt:
    name: nodejs
    state: present

- name: Install rails
  shell: . /root/.bashrc && gem install rails -v 5.1.4

- name: rbenv rehash
  shell: . /root/.bashrc && rbenv rehash
